app:
  image: node:11-alpine
  command: sh -c "yarn install && yarn migrate && yarn seed && yarn dev"
  environment:
    - GRENAGE_API_DB_NAME
    - GRENAGE_API_DB_PASS
    - GRENAGE_API_DB_USER
    - GRENAGE_API_PORT
    - GRENAGE_REPOSITORY_URL
  links:
    - postgres
    - redis
  ports:
    - "3001:3001"
    - "9229:9229"
  volumes:
    - .:/app
  working_dir: /app

postgres:
  image: postgres:alpine
  environment:
    - POSTGRES_DB=${GRENAGE_API_DB_NAME}
    - POSTGRES_HOST=postgres
    - POSTGRES_PASSWORD=${GRENAGE_API_DB_PASS}
    - POSTGRES_USER=${GRENAGE_API_DB_USER}
  ports:
    - "5432:5432"

redis:
  image: redis:alpine
  ports:
    - "6379:6379"
